version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1

    steps:
      - checkout

      - run:
        name: Install Nuget packages
        command:
            nuget restore
            
            

      - run:
          name: Restore packages
          command: 
              dotnet restore

      - run:
          name: Build 
          command: 
              dotnet build

      - run:
            name: Test
            command: 
              dotnet test

      - run:
            name: Packing
            command: 
              dotnet pack
