version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout

      - run:
          name: Restor packages
          command: dotnet restore

      - run:
          name: Build 
          command: dotnet build

      - run:
            name: Test
            command: dotnet test

      - run:
            name: Packing
            command: dotnet pack
